---
 data_config: 
    day_measurements: 96
    week_num: 1
    pred_days: 1
    test_days: 30
 n_trials: 20
 ht_config:
    k_folds: 5
    seed: 42
    task_batch_size: 1
    sample_batch_size: 1
    learning_rate:
      lower_bound: 1e-4
      upper_bound: 1e-2
      log: true
    train_epochs:
      lower_bound: 5
      upper_bound: 20
    finetune_epochs:
      lower_bound: 3
      upper_bound: 10
    lstm_hidden_units:
      lower_bound: 8
      upper_bound: 64
      log: true
