---
 data_config: 
    day_measurements: 96
    week_num: 1
    pred_days: 1
    test_days: 7
    epsilon: 0.1
 opt_config:
    seed: 42
    task_batch_size: 1
    sample_batch_size: 1
    linear_layers: 2
    loss: 'MSE'
    lstm_hidden_units: 32
    finetune_epochs: 5
    learning_rate: 