---
 data_split_constants: 
    timestep: 15
    week_num: 1
    pred_days: 1
    test_days: 7
 n_trials: 10
 ht_config:
    k_folds: 2
    batch_size: 1
    seed: 42
    scheduler_factor: 0.1
    scheduler_patience: 2
    scheduler_threshold: 1e-2
    loss: 'MSE'
    lstm_hidden_units: 32
    linear_layers: 2
    epochs: 5
    learning_rate:
      lower_bound: 5e-4
      upper_bound: 5e-2
      log: true
