#!/bin/bash

# Bash Strict Mode
set -euo pipefail
IFS=$'\n\t'

for file in ./data/iONA_test_aggregated/*
do
    python3 ./task_specific_lstm/source/train.py --filepath "$file" \
                                                 --config "./task_specific_lstm/config.yaml"
done