---
 data_config:
    day_measurements: 96
    week_num: 1
    pred_days: 1
    test_days: 7
    epsilon: 0.1
 n_trials: 10
 seed: 42
 ht_config:
    k_folds: 3
    task_batch_size: 1
    sample_batch_size: 1
    num_inner_steps: 3
    eta_min: 1e-6
    second_order: False
    second_to_first_order_epoch: 8
    loss: 'MSE'
    kappa:
      lower_bound: 1.5
      upper_bound: 5.0
    train_epochs:
      lower_bound: 10
      upper_bound: 30
    lstm_hidden_units:
      lower_bound: 16
      upper_bound: 64
    init_learning_rate:
      lower_bound: 1e-4
      upper_bound: 1e-3
      log: true
    meta_learning_rate:
      lower_bound: 1e-5
      upper_bound: 1e-3
      log: true
