#!/bin/bash

# Bash Strict Mode
set -euo pipefail
IFS=$'\n\t'

python3 ./source/train.py --train_dir "../data/iONA_train_aggregated/" \
                 --test_dir "../data/iONA_test_aggregated/" \
                 --config "./config.yaml"