---
 data_config:
    day_measurements: 96
    week_num: 1
    pred_days: 1
    test_days: 7
 n_trials: 15
 seed: 42
 ht_config:
    k_folds: 5
    seed: 42
    task_batch_size: 1
    sample_batch_size: 1
    train_epochs: 20
    learning_rate:
      lower_bound: 1e-5
      upper_bound: 1e-3
      log: true
    embedding_ratio:
      lower_bound: 0.1
      upper_bound: 0.5
      step: 0.1
