---
 data_config:
    day_measurements: 96
    week_num: 1
    pred_days: 1
    test_days: 7
 tsne_perplexity: 10.0
 n_trials: 10
 seed: 42
 ht_config:
    k_folds: 3
    task_batch_size: 1
    sample_batch_size: 1
    train_epochs: 20
    max_epochs: 100
    patience: 5
    min_delta: 0.0
    loss: 'MSE'
    kappa:
      lower_bound: 1.5
      upper_bound: 5.0
    learning_rate:
      lower_bound: 1e-5
      upper_bound: 1e-3
      log: true
    embedding_ratio:
      lower_bound: 0.02
      upper_bound: 0.06
      step: 0.01
