#!/bin/bash

# Bash Strict Mode
set -euo pipefail
IFS=$'\n\t'

python3 ./data_aggregation/source/segments_metadata.py --data_dir "./data/iONA_train/"
python3 ./data_aggregation/source/segments_metadata.py --data_dir "./data/iONA_test/"

python3 ./data_aggregation/source/aggregate.py --config "./data_aggregation/aggregate_config.yaml"